# Config file

name: Mathscapes Research
url: https://mathscapes.xyz
baseurl: 

permalink: /notes/:title/

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

jekyll-archives:
  enabled: 
    - tags
  layout: archive
  permalinks:
    tag : /notes/tag/:name/

plugins:
  - jekyll-archives

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
